on:
  push:
    branches:
      - main
      - deploy-gha

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # MÃ©thode SSH native sans action externe
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy & restart service
        run: |
          ssh deploy@${{ secrets.SSH_HOST }} "
            set -e
            cd /home/wulfy/dev/node/alexa-oauth
            git pull origin master
            sudo systemctl restart myapp.service
          "